### ISSUE TITLE
AVX build fails

### ISSUE THREAD

**Issue by scorpius** [JiayinCao/SORT#110]
I can compile on xenial and bionic with no errors, but the binary doesn't run because my cpu does not support AVX. So I set **ENABLE_AVX_OPTIMIZATION       "NO"** and it fails to build with this error:

`/home/anthony/build/SORT/src/simd/simd_wrapper.h: In function ‘simd_pick_ps(float __vector(4) const&, float __vector(4) const&, float __vector(4) const&)’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:204:1: error: inlining failed in call to always_inline ‘_mm_blendv_ps(float __vector(4), float __vector(4), float __vector(4))’: target specific option mismatch
 _mm_blendv_ps (__m128 __X, __m128 __Y, __m128 __M)
`

**Comment by scorpius** [comment]
I found a workaround. By also disabling **ENABLE_SSE_OPTIMIZATION** it compiles and runs. But my i7 cpu has sse4_2, so am I losing some performance?

**Comment by JiayinCao** [comment]
I would not suggest you to disable SSE, it is highly unrecommended.
I can take a look at it after I get home today,

I'm still working on the Last of Us part II in our office now.

**Comment by JiayinCao** [comment]
In a nutshell, this following line is part of SSE4.1 standard.
return _mm_blendv_ps( get_sse_data(b) , get_sse_data(a) , get_sse_data(mask) );
please check further detail here
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_blendv_ps&expand=456
The problem happens because I didn't specify any specific SSE standard in CMake, gcc may choose the older one unlike the other two OSs, which are fine in this case.

Since SSE 4.1 is widely available on literally all machines these days, I have no plan to support anything older than it. Technically speaking, it can be done in CMake. But I would not want to spend my time on adapting it so that it works on older machines, which I don't even have at home.

510337f484ada8348c1d438ef16d8511d63d3e84 fixed the problem on Ubuntu. I think you can disable AVX and enable SSE on your build now. Make sure you use QBVH for ray tracing, it is a lot faster than BVH or OBVH without AVX. Actually, QBVH is the default spatial acceleration structure in SORT.

Problem solved, closing this ticket.
Thanks for reporting it.

**Comment by scorpius** [comment]
It still fails to compile with the new changes. If I change AVX to SSE on line 208, it compiles cleanly and renders a little faster. Maybe it was a typo? Here's what I used:

```
if(ENABLE_SSE_OPTIMIZATION)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse4.1")
endif()

```

**Comment by JiayinCao** [comment]
You are right about the typo.
712633027bf02ed9214d24fc77a33281ca092568 fixed it.

**Comment by scorpius** [comment]
Thanks. I can now render 2.5x faster with SSE on, and AVX off. I really like this renderer!
